### ISSUE TITLE
calendar-widgets roadmap

### ISSUE THREAD

**Issue by 9mbs** [9mbs/calendar-widgets#155]
- [x] Remove Monorepo, its too much to maintain. 
- [x] Deprecate most helpers 

## Whats going to be in the package?
The purpose of the project is to provide easy-to-use, un-styled React components that mimic the behavior you might see in popular Calendar applications. 

- [ ] React Components
  - [ ] `Calendar` _in progress_
  - [ ] `DraggableDay` _in progress_
  - [ ] `DraggableWeek`
  - [ ] `DraggableCalendar`
- [ ] Context 
  - [ ] `useCalendarWidgetsContext`
