### ISSUE TITLE
move `dayName` component to `Calendar.dayName` as a optional prop

### ISSUE THREAD

**Issue by 9mbs** [9mbs/calendar-widgets#200]
There is a block of code in the `src/react/Calendar/Calendar.tsx` file that is used to display the days of week. e.g `S, M, T, W, T, F, S` this code block is currently hardcoded into the `return` statement of the `Calendar` component. 

We should modify this bit to live as a customizable component that library users can define themselves. Same as the `dayComponent` prop we already have defined in this file.

_This is the block that should be extracted from the return statement_
```tsx
// ...
<div style={{ display: 'flex' }}>
    {dayNames.map((dayName, idx) =>
      <div key={idx} style={{ display: 'inline-block', width: '14.28%', textAlign: 'center' }}>
        {dayName}
      </div>
    )}
</div>
// ...
```

## Tasks
- [ ] Create a new prop in the `CalendarProps` interface called `dayNameComponent` that allows users to customize the Day Names components
- [ ] If the `dayNameComponent` prop is not provided by the user, assign the default code block shard above. ☝ 
- [ ] If the `dayNameComponent` prop is provided by the user, map over the days of the week and render the custom `dayNameComponent` for each day.
- [ ] (Optional) Create a new story in Storybook to test the happy/unhappy cases here.
