### ISSUE TITLE
Create and document basic internalization-useage with `format.js`

### ISSUE THREAD

**Issue by 9mbs** [9mbs/calendar-widgets#219]
## Tasks
- [ ] Create an example `Calendar` that utilizes the `format.js` library 
- [ ] Document _why_ this is needed
- [ ] Document _how_ to implement
- [ ] Localization should always be optional
