### ISSUE TITLE
rebrand to calendar-widgets

### ISSUE THREAD

**Issue by 9mbs** [9mbs/calendar-widgets#40]
After a year of operating under the generalized name WhileThisCompiles, i've decided to rebrand to a more professional appearance - **Calendar Widgets**! The rebrand is more than just a name change, I'm planning on investing a fair amount of my time and resources into the development of this SDK and API. I'm also planning a UI library which is intended to be the core product offering from the `calendar-widgets` package. 

## Changes
- **BREAKING CHANGE** The website and API are now hosted on https://www.calendar-widgets.com
- The SDK is going to be further developed under the scope `calendar-widgets`.  The scope `@whilethiscompiles/calendar` is depreciated but will continue to exist on NPM as is.

## Tasks
- [x] Update DNS records
- [x] Publish `calendar-widgets`
- [x] Update docs to point towards calendar-widgets
- [x] Update repo to calendar-widgets

**Comment by 9mbs** [comment]
This process has been completed, feel free to carry on under the new package name `calendar-widgets`
